codeforjapan/decidim-cfj

Dockerfile, docker-compose.yml
- 環境構築のため
- 公式ドキュメントを見た感じ、entrypointは `rails server -b 0.0.0.0`でいい気がします。
https://docs.decidim.org/en/develop/docker/
Dependency MR
- https://github.com/codeforjapan/decidim-cfj/pull/10
- https://github.com/codeforjapan/decidim-cfj/pull/8
- Related to #12
=> Fix entrypoint on app docker container

.gitignore, app/views/decidim/proposals/admin/proposals/_form.html.erb
To fix #24, I removed the `value:` from the form field because it is not needed to translate before the form rendering. 
- Fixes #24
=> fix #24 fix editing error

.gitignore, app/models/decidim/proposals/admin/proposal_form.rb, app/models/decidim/proposals/proposal_wizard_create_step_form.rb, config/initializers/decidim.rb
提案のタイトルのバリデーションを変更するため。
https://github.com/codeforjapan/decidim-cfj/issues/1
上記のissueでローカルのファイルが優先されるとあったので、全く同じディレクトリに全く同じ名前のファイルを追加したことで解決できました。
これで本体のDecidimのupdateに追随できるのか正確に把握していない点が残課題です。
- Related to #23 
  | Before | After
-- | -- | --
Admin |<img width="1664" alt="Lesch_LLC" src="https://user-images.githubusercontent.com/35568422/97174646-b5c52080-17d5-11eb-800c-88a4c1d1245f.png">|  <img width="1667" alt="Lesch_LLC" src="https://user-images.githubusercontent.com/35568422/97174476-80203780-17d5-11eb-96b5-dbd318e341b2.png">
User |<img width="1459" alt="提案を作成_-_提案_-_めいし_問題_渦巻き_話_ひかくする。_-_Lesch_LLC" src="https://user-images.githubusercontent.com/35568422/97156650-5ad20000-17ba-11eb-8e0b-c12c0b8cb098.png">   |  <img width="1528" alt="提案を作成_-_提案_-_めいし_問題_渦巻き_話_ひかくする。_-_Lesch_LLC" …
=> 提案のタイトルのバリデーションを8文字にする

docker-compose.yml
- docker-compose up を動作させます。詳細は #69 に書いたとおりです。
- Fixes #69
=> Upgrade docker-compose version to enable extenstion fields

app/assets/stylesheets/decidim.scss, app/assets/stylesheets/kakogawa.scss, app/views/layouts/decidim/_head_extra.html.erb
新しいCSSを追加したら、production で assets pipline エラーになった。
とりあえずの修正。
=> don't use new css

app/assets/stylesheets/decidim.scss
=> fix #27 change css for fix styling

config/locales/ja.yml
=> fix #37 承認済みを支持済みに

app/assets/stylesheets/decidim.scss
=> close デザイン修正 #89 change style

config/locales/ja.yml
=> change translation

db/migrate/20201029125846_change_direct_message_types_to_users.rb, db/schema.rb
=> fix #91 デフォルトでダイレクトメッセージを受け取らない設定に

app/assets/stylesheets/decidim.scss
=> fix #45 add nowap style

config/initializers/decidim.rb
=> fix #84 enable html_header_snippets

config/locales/ja.yml
=> fix #104 translation

app/views/decidim/devise/registrations/new.html.erb, config/locales/ja.yml
#76 を解決するため、placeholderと注意書きを追加しています。
- Fixes #76
=> add notice for nickname and placeholder

Gemfile, Gemfile.lock, app/uploaders/decidim/application_uploader.rb
See also https://github.com/codeforjapan/decidim-cfj/issues/101#issuecomment-719880381
- Fixes https://github.com/codeforjapan/decidim-cfj/issues/101
=> Fix for issue 101: ValidationError during open data export

config/initializers/carrierwave.rb
- 本番環境と、検証環境のAWS のs3バケットを別に用意するため。
- Fixes #?
=> Add environment value :AWS_BUCKET_NAME

bin/get_comments.sh
加古川市のコメント一覧をCSVにエクスポートするスクリプトを書いた
=> add data loading script

decidim-user_extension/README.md
Decidim::UserExtensionモジュールについて、README.mdに説明を追加しておきます。
* データの保存と管理画面での監査について
* 途中で設定を変更した場合の挙動
特になし
=> decidim-user_extension: update README

decidim-user_extension/app/views/decidim/account/show.html.erb, decidim-user_extension/app/views/decidim/devise/registrations/new.html.erb
=> fix extension check

Gemfile, Gemfile.lock, config/newrelic.yml
パフォーマンス監視のためのnew Relicの追加
- Fixes #?
=> add new Relic gem

Gemfile.lock
#199 と同様の修正をmasterブランチに適用する修正です。
**注意: このPRをマージするとmasterが更新されます。**
see: https://github.com/rails/rails/issues/41750
- Fixes #198
=> update mimemagic (for master branch)

Gemfile, Gemfile.lock
#204 と同様の修正をmasterブランチに対して行うものです。
- Related to #204
=> Update mimagic 0.3.10 for master

decidim-user_extension/lib/decidim/user_extension/concerns/controllers/needs_user_extension.rb, spec/sytem/needs_user_extension_spec.rb
ユーザー拡張属性を使わない場合の挙動の修正です。
- Fixes #206
=> Fix #206; not redirect when user_exntesion is disable

config/locales/ja.yml
localeファイルを追加しておきます
- Related to #187
=> add locale for user_extension_authorization_handler

app/commands/decidim/admin/process_participatory_space_private_user_import_csv.rb, app/helpers/decidim/paginate_helper.rb
🎩 What? Why?
(We should remove the fix when upgrade Decidim 0.24.0.)
📌 Related Issues
Fixes #219
=> Backport Decidim::PaginateHelper from v0.24.0

config/locales/ja.yml
#233 に対する修正で、config/locale/ja.yml を追加します。
- Fixes #233
=> Fix locale of proposals

CHANGELOG.md
#230 のCHANGELOG.mdを追加します。
書き方は[本家のCHANGELOG.md](https://github.com/decidim/decidim/blob/release/0.24-stable/CHANGELOG.md)と揃えつつ、更新されなかった見出しは省略するようにしてみました。
- Fixes #230
=> Add Changelog (CHANGELOG.md)

deployments/docker-compose.yml
- NEW_RELIC_APP_NAMEの環境変数のタイポの修正
- Related to #235
- Fixes #?
=> chore: fix typo decidem -> decidim on NEW_RELIC_APP_NAME

config/newrelic.yml, deployments/staging/00_env_options.config
コスト面からレートリミットを回避するため、本番以外でNew Relicをoffにする
- Fixes #255
=> chore: Turn off New Relic except production

config/locales/ja.yml
#260 の指摘に対する修正で、住所 -> アドレス に変更します。
- Fixes #260
=> Fix locale file: `decidim.errors.not_found.content_doesnt_exist`

public/robots.txt
bot が障害の原因になるのでその対応
- Fixes #254
=> Update robots txt

config/locales/ja.yml
#44 の対応として「すべて既読にする」を「すべての通知を削除する」に変更します。
- Fixes #44 
適用後の画面は以下のようになります。
=> Fix message of `mark_all_as_read`

config/locales/endorse_ja.yml, decidim-comments/app/queries/decidim/comments/sorted_comments.rb
#281 に関連して、「endorsement」に当たる日本語を「オススメ」に変更するためのYAMLファイル
- Related to #281
=> Fix messages endorsement in JA; use オススメ

config/initializers/carrierwave.rb
画像の閲覧時間制限を伸ばします（約100年）。
https://meta.diycities.jp/assemblies/nazo/f/286/proposals/297
=> Fix config of image expiration

config/locales/awesome.ja.yml
未翻訳だったところについて、最新版の翻訳ファイルを使って更新しました。
なお、0.7.0では使われていなかったところは一部削除しています。
=> Decidim Awesomeの翻訳ファイルを更新

docs/UPGRADE.md
#325 の対応です。まだ追加があるかもしれません。
- Fixes #325
=> Add UPGRADE.md

app/forms/decidim/proposals/proposal_wizard_create_step_form.rb
aa227bb1606461461eb0812238042e81ad729bfe に続いて、Decidim v0.24.3での修正をフィードバックします。
- Related to #312
=> Feedback from decidim/decidim v0.24.3

bin/get_user_data.sh
`bin/get_user_data.sh` を作って配置しました。ユーザーのデータを取得するときに使うものです。
EC2インスタンスを別途立てて、そちらに置いているものです。
=> add new script

Gemfile.lock
newrelic_rpmのgemのバージョンが上がっていたので、（別に困っているわけではないですが）bundle updateしておきます。
- Fixes #?
=> Update newrelic_rpm gem

deployments/production-v0-23-5/00_env_options.config, deployments/staging/00_env_options.config
regionの切り替えです。
aws側で変数の設定は完了しています。
- Fixes #345
=> use aws ses ap-northeast-1 region

config/locales/file_validators_ja.yml
`file_validators` gemは日本語のlocale fileが入っていなかったので、追加しておきます。
=> Add ja locale file for file_validators gem

deployments/production-v0-24-3/00_env_options.config
=> fix production redis env

app/controllers/decidim/debates/versions_controller.rb
descriptionがない場合があるようなので修正します。
- Related to #359
=> Fix error in /debates/versions

.github/workflows/rails-test.yml
GitHub Actionsでのテストの実行回数を減らして、無駄にテストを実行させないようにします。
=> GitHub Actions: reduce number of tests

docs/UPGRADE.md
`UPGRADE.md`に説明を追加します。
- Related to #330
=> UPGRADE.md: Add comments about `decidim-user_extension`

config/locales/ja.yml
日本語の訳文を追加します。
#366 と合わせて使うものです。
- Related to #366
=> Add JA locale data for verification

app/commands/decidim/verifications/authorize_user.rb, app/controllers/decidim/verifications/authorizations_controller.rb, spec/commands/decidim/verifications/authorize_user_spec.rb
#366 のmasterに対する修正です。
- Related to #366
=> Fix AuthorizeUser; "Fix verification report with multitenants"

bin/get_user_data.sh, lib/tasks/download.rake
ユーザーデータダウンロード用のRakefileを作成しました。これをアプリケーションサーバ上で実行すると、tmp/user_data.csv というファイルが作成されます。
- Related to #382
=> add rake task

decidim-user_extension/config/locales/ja.yml
翻訳が抜けているところがあったのを修正します。
- Related to #387 （直接は関係ないのですが…）
=> Add some locale entries for user_extension module

app/views/decidim/participatory_processes/admin/participatory_process_groups/_form.html.erb
＃401 の修正で、公開範囲の部分が画面上に表示されなくなります
- Fixes #401
=> fix: #401 remove visibility column

Gemfile, Gemfile.lock, config/initializers/omniauth_line.rb, config/locales/line_login.en.yml, config/locales/line_login.ja.yml, config/secrets.yml, omniauth-line_login/.gitignore, omniauth-line_login/.rspec, omniauth-line_login/.rubocop.yml, omniauth-line_login/Gemfile, omniauth-line_login/Gemfile.lock, omniauth-line_login/README.md, omniauth-line_login/Rakefile, omniauth-line_login/bin/console, omniauth-line_login/bin/setup, omniauth-line_login/lib/omniauth-line_login.rb, omniauth-line_login/lib/omniauth/line_login/error.rb, omniauth-line_login/lib/omniauth/line_login/version.rb, omniauth-line_login/lib/omniauth/strategies/line_login.rb, omniauth-line_login/omniauth-line_login.gemspec, omniauth-line_login/sig/omniauth/line_login.rbs, omniauth-line_login/spec/spec_helper.rb
#380 のやり直しです。
#403 でいったんrevertしたものを再度revertし、さらに修正を追加します。
This reverts commit 168abb5e605329a7f133f4abd3190160e211e41f, reversing
changes made to bedf8004fe6844dabde202b39ab2d8468c3b0b83.
- Related to #403 , #380
=> Retry LINE login

.github/workflows/build_image.yml
decidimのversion更新の際にimageのbuild自動化するためのworkflowの追加です
=> create: build_images workflow

decidim-comments/app/controllers/decidim/comments/comments_controller.rb, spec/sytem/comment_sort_spec.rb
#409 で追加したクッキーについて、同意がない場合は無視するよう修正します。
- Related to https://github.com/codeforjapan/decidim-cfj/pull/409
=> Use cookie only with agreement

.github/workflows/deploy.yml
=> fix: deploy.yml version

app/forms/decidim/debates/close_debate_form.rb
=> Fix `Decidim::Debates::Form`

.github/workflows/rails-test.yml
GAにnodeとyarnを追加します。合わせてprecompileも実行します。
キャッシュ周りはまだ手つかずです。
- Fixes #?
=> GitHub Actions: Add node and yarn

.github/workflows/rails-test.yml
テストの際にassetsをキャッシュするようにしてみます
- Related to #416
=> GitHub Actions: Use cache

Dockerfile
ecsへの移行の関係でdocker container内にcurlを追加します
- Fixes #?
=> feat: add curl

CHANGELOG.md
=> feat: update CHANGELOG.md

lib/tasks/replace_to_null.rake
replace_to_null taskに参加型プロセスの編集バグを修正するコマンドの追加です
=> feat: add replace to null ParticipatoryProcess command

config/initializers/decidim.rb
`get_comments.sh`を実行できるように、`max_complexity`を変更します。
とりあえずは100,000にしてみました。
=> Set `max_complexity` of `GraphQL::Schema`

config/initializers/decidim.rb, lib/tasks/replace_to_null.rake
get_comments.shを実行できるように、max_complexityを変更します。
=> Set max_complexity of GraphQL::Schema

docs/UPGRADE.md
`docs/UPGRADE.md`にはまだなかったファイルの説明を追加しておきます。
- Fixes #?
=> Add some items in UPGRADE.md

docs/UPGRADE.md
#428 と #429 で対応済みの削除したファイルを、ドキュメントからも削除します。
- Related to #428 , #429
=> doc: Remove fixed(removed) files in UPGRADE.md

lib/tasks/replace_to_null.rake
参加スペースの提案componentの編集でエラーが出る問題の修正
- Fixes #?
=> feat: add replace to null decidim_proposals command

config/environments/development.rb, deployments/etc/nginx/conf.d/default.conf
<del>CSRF対策で、開発環境ではポートの違いを考慮しないように設定を変更します。</del>
↑Rails側ではなくて、nginx側の設定を変更して解決する方針に変更しました。
- Fixes #439
=> Fix nginx.conf; add $proxy_port to Host header

deployments/etc/nginx/conf.d/default.conf
=> hotfix: deployments nginx conf

Gemfile, Gemfile.lock, app/packs/src/decidim/decidim_awesome/editors/editor.js
#434 の問題decidim awesome側で既に修正されていたのでそれを取り込む対応です。
- Fixes #434
=> fix: user upload image error

config/locales/ja.yml
#374 の対応で、collaborative draftを「共同草案」にします。
- Fixes #374
=> locale: fix collaborative_draft

docs/UPGRADE.md
#455 に関する説明を UPGRADE.md に追加しておきます。
- Related to #455
=> Add comments for `Decidim::ImageUploader` in UPGRADE.md

lib/tasks/comment.rake
対象のなくなったコメントを消すバッチです。
`bundle exec rake comment:remove_orphans` で実行します。
- Fixes #?
=> Add task comment:remove_orphans

.github/workflows/deploy.yml
=> hotfix: ci create_env

.github/workflows/deploy.yml
=> fix: ci credentials

.github/workflows/deploy.yml
=> fix: ci permission

.github/workflows/deploy.yml
=> fix: remove working directory

.github/workflows/deploy.yml
=> fix: change checkout directory

.github/workflows/deploy.yml
=> fix: add debug_log

config/initializers/decidim.rb, config/secrets.yml
=> feat: add geo cording osm

.github/workflows/deploy.yml, .github/workflows/rails-test.yml
docker buildをcacheするように変更
- Fixes #?
=> refactor: deploy actions

app/packs/stylesheets/decidim/cfj/media_print.scss
close #484
Change background color from red to white.
- Fixes #?
=> change backgroundcolor from red to #FFFFFF

.github/workflows/deploy.yml
=> refactor: change deploy env name

docs/DEVELOPMENT.md
* セットアップ時に`default_locale` を変更しないよう修正
- Fixes #490
=> Fix setup instructions

docs/UPGRADE.md
CSSファイルのパスが変わったので、UPGRADE.mdに反映します。
- Fixes #?
=> Fix UPGRADE.md

config/initializers/carrierwave.rb, config/storage.yml
awsのaccess keyとsecretをiam role から取得するようにします
- Fixes #?
=> refactor: use s3 iam role

app/commands/decidim/comments/destroy_all_comments.rb, app/commands/decidim/organizations/destroy_organization.rb, lib/tasks/delete.rake
#501 について一部エラーになることがあったようなので修正します。
- Related to #501
=> `delete:destroy_all`の修正

app/packs/src/decidim/decidim_awesome/editors/editor.js
=> fix: html editor

app/packs/src/decidim/decidim_awesome/editors/editor.js
タグエディターを開くと`<br>`要素がなくなってしまう件を修正します。
- Fixes #?
=> Fix HTML Tag Editor

decidim-comments/config/locales/eu.yml, decidim-comments/config/locales/pl.yml, decidim-comments/config/locales/sv.yml
decidim-commentsのconfig/localeで、v0.26.5本体での修正が反映されていないファイルがあったので修正します。
=> Sync locale files in v0.26.5

Gemfile.lock
new relicのgemが新しいバージョンが出ていたので更新します
- Fixes #?
=> refactor: update newrelic gem

config/locales/decidim_awesome.ja.yml, config/locales/ja.yml
DecidimAwesomeの翻訳ですが、まだマージされていないものがあるようなので、こちらに追加しておきます。
cf. https://github.com/decidim-ice/decidim-module-decidim_awesome/pull/209
=> Add locale files for DecidimAwesome

decidim-user_extension/app/forms/decidim/user_extension_form.rb
=> refactor: add required

decidim-user_extension/config/locales/ja.yml
新規登録時のエラーメッセージが正しく表示されていなかったものを修正します。
- Fixes #?
=> Fix error message in flash

config/locales/polis_ja.yml
Pol.isの管理画面（設定画面）にて、ヘルプメッセージを表示させるようにします。
- Fixes #?
=> polis admin: Add help messages for settings

app/cells/decidim/amendable/amend_button_card_cell.rb, config/locales/ja.yml, config/locales/polis_ja.yml
Fix amendable_fields in Decidim::Amendable::AmendButtonCardCell #539
- Fixes #?
=> Fix amendable_fields in Decidim::Amendable::AmendButtonCardCell

app/views/decidim/blogs/posts/show.html.erb
ブログの新規投稿をしたらいきなりエラーが出るので調べてみたところ、viewのテンプレートに変更があったようなので反映させます。
（公式の投稿というのができてそうで、その対応のための変更だったようです）
- Fixes #?
=> Update a view file of `blogs#show`

app/views/decidim/participatory_processes/admin/participatory_process_groups/_form.html.erb
`app/views/decidim/participatory_processes/admin/participatory_process_groups/_form.html.erb`がv0.27.4で更新されていたのを反映します。
また、合わせて #402 での修正を適用しています。
- Related to #401
=> Update form file in participatory_process_groups

config/locales/ja.yml
翻訳抜けがあったようなので追加します。
- Fixes #?
=> Add locale item user.avatar

config/locales/ja.yml
本家のv0.27.4で反映済みのlocale設定を削除します。
- Fixes #?
=> Update config/locale file from v0.27.4

decidim-user_extension/app/views/decidim/account/show.html.erb
v0.27.4でのdecidim-core/app/views/decidim/account/show.html.erb の更新を反映します。
- Fixes #?
=> Update account#show in v0.27.4

.github/workflows/deploy.yml, docs/DEPLOYMENT.md
github actionsのprdのversion更新
- Fixes #?
=> refactor: update github action prd version

.github/workflows/main.yaml
=> fix: action output step name

.github/workflows/main.yaml
=> fix: action output name

.github/workflows/_build.yaml, .github/workflows/_check.yaml, .github/workflows/main.yaml
=> fix: action add secret

.github/workflows/main.yaml
=> fix: add action needs

Gemfile, Gemfile.lock
dailyの通知の送信時にエラーが起こっている問題の修正
- Fixes #?
=> feat: update sidekiq version

.github/workflows/main.yaml
productionのリリースがうまく動かない問題の修正
- Fixes #?
=> fix: deploy action

docs/DEPLOYMENT.md, docs/DEVELOPMENT.md
=> refactor: update docs

docs/DEVELOPMENT.md, docs/UPGRADE.md, spec/support/active_storage_helpers.rb, spec/system/admin_officializations_user_extension_spec.rb, spec/system/comment_sort_spec.rb, spec/system/needs_user_extension_spec.rb, spec/system/user_profile_spec.rb
=> fix: update docs

Dockerfile
=> fix: remove decidim comments from Dockerfile

decidim-user_extension/app/commands/concerns/decidim/user_extension/create_omniauth_commands_overrides.rb, decidim-user_extension/app/commands/concerns/decidim/user_extension/update_commands_overrides.rb, decidim-user_extension/app/views/decidim/devise/registrations/new.html.erb
v0.27.4との差分があったので、取り込みます。
- Fixes #?
=> decidim-user_extensionをv0.27.4に合わせて更新

.rubocop_rails.yml, app/commands/decidim/organizations/destroy_organization.rb, app/commands/decidim/participatory_processes/destroy_all_participatory_processes.rb, lib/tasks/delete.rake
delete.rakeが動かないので修正です。
- Fixes #?
=> fix: delete.rake

Gemfile.lock, config/newrelic.yml
new relicのgemの更新、収集するログレベルの変更
- Fixes #?
=> refactor: update new relic gem

docs/UPGRADE.md
=> fix: gem version

app/commands/decidim/organizations/destroy_organization.rb
organizationの削除時に必要なものが抜けていたので追加です
- Fixes #?
=> feat: update destroy organization

app/commands/decidim/search.rb, db/schema.rb
`Decidim::Search`を上書きして、public_spacesしか検索しないよう修正します。
また、db/schema.rbが更新されていなかったので合わせて更新しておきます。
- Related to #615
=> 検索対象をpublic_spacesのみにするよう修正

docker-compose.yml, docs/DEVELOPMENT.md
#627 の対応で、DockerでもRedisを使えるよう、docker-compose.ymlを修正します。
- Fixes #627
=> fix: Use Redis with docker compose

config/environments/production.rb
productionにsession storeの対応を追加
- Fixes #?
=> fix: refactor session

public/robots.txt
botのrequestを全て落とすように変更
- Fixes #?
=> Refactor/update robots.txt

.github/workflows/_check.yaml, config/locales/ja.yml
( https://github.com/codeforjapan/decidim-cfj/pull/647 のやり直しで、mainブランチ向けです)
highlighted_processesなどが「注目の参加型プロセス」のような訳語に置き換えます。
- Related to https://github.com/codeforjapan/decidim-cfj/pull/647
=> fix locale highlighted process

config/locales/ja.yml
公開プロフィールのページで、翻訳がおかしかったところを修正します。
- Fixes #?
=> fix: Add translation for following count

config/initializers/decidim_override.rb
参加スペース管理者による編集についての修正です。
https://github.com/decidim/decidim/pull/13544 と同様の変更をv0.28.4に対して行うものです。
- Fixes #?
=> fix patch same as https://github.com/decidim/decidim/pull/13544

config/locales/en.yml, decidim-user_extension/config/locales/en.yml
英語版の方で足りてなさそうなものを追加しておきます
- Fixes #?
=> fix: translations in English

app/packs/stylesheets/decidim/cfj/typography.scss
=> refactor: update css

.github/workflows/_check.yaml, docker-compose.yml, docs/DEVELOPMENT.md
本番のpostgresのversionを上げたので開発環境も合わせて変更します
- Fixes #?
=> refactor: update postgres v14

config/environments/production.rb, config/initializers/carrierwave.rb
=> fix: change expire

config/locales/ja.yml
navigation mapを使うと翻訳抜けでエラーになる場合があったので修正します。
- Fixes #?
=> add transations

app/views/layouts/decidim/_mailer_logo.html.erb
mailのヘッダーロゴで、出ていたエラーの修正
undefined method `rails_blob_path'
- Fixes #?
=> fix: mail logo bug

decidim-user_extension/app/views/decidim/account/_user_extension.html.erb, decidim-user_extension/app/views/decidim/devise/registrations/_user_extension.html.erb
=> fix: gender is also required in registration form

.github/workflows/_check.yaml
GitHub Actionsで使われていない環境変数があったので消しておきます。
- Fixes #?
=> fix: GA: remove unused envvar

docs/UPGRADE.md
docs/UPGRADE.md をv0.28.5に合わせて更新します。
- Fixes #?
=> update `UPGRADE.md` for v0.28.5

config/locales/ja.yml
v0.29.2で指定不要となったlocales/*ja.ymlのデータを消します。
- Fixes #?
=> fix: old locales data

Gemfile.lock
graphqlとrackとnokogiriのgemを、現状のgemの指定が許す範囲での最新版に更新します。
- Fixes #?
=> fix: update graphql, rack, and nokogiri

Gemfile.lock
REXMLを更新します。
- Fixes https://github.com/codeforjapan/decidim-cfj/security/dependabot/34
=> fix: bundle update rexml
