codeforjapan/decidim-cfj

Dockerfile
docker-compose.yml

開発環境作成のため、Dockerのヴァージョンを0.23.0.dev のバージョンからlatestに変更
0.23.0.dev は存在しない。latestで追いかけて、本家のリリースが完了したら、0.23で固定する予定。
https://hub.docker.com/r/decidim/decidim/tags
- Related to #7

Fix docker tag from not exist version 0.23.0.dev to latest

---

Dockerfile
docker-compose.yml

- 環境構築のため
dokcerコンテナで、外部からの接続には、ポスグレのコンテナにパスワードの設定が必要
アプリ側にもissueの通り必要。
>POSTGRES_PASSWORD
>
>This environment variable is required for you to use the PostgreSQL image. It must not be empty or undefined. T
現状、appのコンテナのポスグレユーザー名がデフォルトのため、ポスグレ側にユーザー名は設定しなくても問題ない。
しかし可読性の観点から、意識的に設定するようにした。
https://hub.docker.com/_/postgres
>POSTGRES_USER
>
>This optional environment variable is used in conjunction with POSTGRES_PASSWORD to set a user and its password. This variable will create the specified user with superuser power and a database with the same name. If it is not specified, then the default user of postgres will be used.
Dependency commit : https://github.com/codeforjapan/decidim-cfj/pull/10/commits/ec4647855ebc6030b3169fce337f9ec703ca1a9d
- Related to #9

Add postgres password environment setting in docker

---

docker-compose.yml

開発効率改善のため
環境変数`RAILS_LOG_TO_STDOUT` によりrailsのログが、標準出力にでています。しかし、rails自体の挙動か
/log/development.logにも出力されていました。
dockerはホストとのioの速度が遅いため、このあたりの挙動がボトルネックになっていると考えられます。
よって、下記を参考に不要なディレクトリを匿名ボリュームに入れました。匿名ボリュームだと、関連コンテナが削除された際に自動で削除されるので、名前付きボリュームより取り回しやすいと判断しました。
https://qiita.com/shotat/items/57d049793605ffc20135
計測してませんが、体感では許容できるくらいまで速くなりました。 :rocket:
- Related to #19

Put unnecessary directories on docker anonymous volumes

---

db/seeds.rb
lib/monkey_patching_faker.rb

bin/rails db:seed のコマンドに失敗する #14 の件ですが、原因が気になったので調べたところ、
* slugの生成でlocaleが:jaのときには日本語の文言が使われる（！）
* 一方で、Decidimではslugは英数字しか許さない（以下を参考）
https://github.com/decidim/decidim/blob/8e237fb075418a840b94275f5dafba7b374dc828/decidim-core/lib/decidim/participable.rb#L97-L99
という理由でエラーになっていることが分かりました。
これはその回避案で、Faker::Internet.slugでlocaleに関わらずenにして出力するよう修正するpatchです。
- Related to #14

fix rails db:seed

---

config/environments/development.rb
config/routes.rb

ローカルの開発環境で、LetterOpener(とLetterOpenerWeb)を使ってメールの確認ができるようにするものです。
これを使えば、実際にメールは送信されなくなり、Webで確認できるため、架空のメールアドレスを使って動作確認ができます。
- Fixes #?

use LetterOpener in development

---

app/assets/stylesheets/decidim.scss

Replaces the up and down semi-triangles with thumbs up/thumbs down embedded SVG to make their function more clear on first glance.
- Fixes https://github.com/codeforjapan/decidim-cfj/issues/41
- [N/A] Add `CHANGELOG` upgrade notes, if required
- [N/A] If there's a new public field, add it to GraphQL API
- [N/A] Add documentation regarding the feature 
- [N/A] Add/modify seeds
- [N/A] Add tests
- [N/A] Another subtask

Replace ^ v icons with thumbs to make their action more clear

---

app/uploaders/decidim/application_uploader.rb

アドミンUIにある設定→ホームページ→ヒーロー画像からアップロードしたら`IntegrityError: The file is not attached to any organization`エラーが`application_uploader.rb`の`validate_inside_organization`に発生します。このPRはこの問題の一部を直します。
暫定的な解決なので、decidimの側ではこのエラー直したら`application_uploader.rb`を削除すべきだと思います。
- Related to https://github.com/codeforjapan/decidim-cfj/issues/18 and https://github.com/decidim/decidim/issues/6720

Temporary fix for https://github.com/decidim/decidim/issues/6720

---

.rspec
Gemfile
Gemfile.lock
config/application.rb
spec/rails_helper.rb
spec/spec_helper.rb

decidim-coreの設定も参考にしつつ、rspecを導入してみます。
- Fixes #42
(nothing)

use rspec instead of minitest

---

app/assets/stylesheets/kakogawa.scss
app/views/layouts/decidim/_head_extra.html.erb

Create custom css as `/assets/stylesheets/kakogawa.scss`
管理画面で<head>内のカスタム項目を追加できるはずだったが、なぜか追加できなかったので暫定対応
- Fixes #25

added custom stylesheet

---

app/assets/javascripts/decidim/editor.js.es6

Minor fix to https://github.com/codeforjapan/decidim-cfj/pull/85 to make sure images display on second edit.
- Related to https://github.com/codeforjapan/decidim-cfj/issues/11

fix displaying images on second edit

---

app/assets/stylesheets/forms.scss
app/views/decidim/account/_user_extension.html.erb
app/views/decidim/devise/registrations/_user_extension.html.erb
app/views/decidim/devise/registrations/new.html.erb

#78 の対応として、ラジオボタンを`<fieldset>`でくくった上、そのマージンをテキストボックスと揃えてみました。
ついでにpartialを使って拡張部分を別ファイルに切り出しています。
- Fixes #78 
修正後の画面は以下です：

性別欄と職業欄のマージンを修正

---

app/assets/stylesheets/buttons.scss

#46 の修正ですが、`/app/assets/stylesheets/decidim.css`はいじらず別ファイルに切り出して追加しました。
- Fixes #46
Before:
After:

centerize a message in social button

---

.cloudformation/ecr.yml

- CI/CDの作成で、AWS ECRリソースの作成に使用したCloud Formationを追加します。
- 普段は見えなくてもいいので、.始まりのフォルダ名にしてみました。
- Related to #56

Add Cloud Formation template for create ECR

---

.github/workflows/build-and-push.yml

- staging動作環境デプロイのための定期ビルドのワークフローを追加します。
- 仮で、時間は18時にしてます。
sample: https://github.com/komtaki/decidim-cfj/actions/runs/339882859
- Related to #110

Add Github Action staging build & push workflow on schedule

---

.github/workflows/rails-test.yml
spec/spec_helper.rb

pull requestのタイミングでrspecとrubocopを実行させるGitHub Actionsです。
ついでにrubocopを動かしたらrspecの関連ファイルが引っかかったので、合わせて修正しておきます（そうしないとこのPRが通らない…）。
- Related to #117, #118 
(nothing)

execute RSpec and RuboCop for pull requests

---

docker-compose.yml

- Docker開発環境のpostgresのversionをv12で固定する
- 本番環境がv12.3だったので、それに合わせる
- 公式のdocker hubにv12.3はなかったので、v12
- 前のvolumeが残っている場合は、下記のようなエラーで起動できないので、削除してください。
```
taki@tari:~/develop/decidim-cfj$ docker-compose logs pg
Attaching to decidim-cfj_pg_1
pg_1   |
pg_1   | PostgreSQL Database directory appears to contain a database; Skipping initialization
pg_1   |
pg_1   | 2020-11-03 06:07:05.828 UTC [1] FATAL:  database files are incompatible with server
pg_1   | 2020-11-03 06:07:05.828 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 13, which is not compatible with this version 12.4 (Debian 12.4-1.pgdg100+1).
```
- Related to #122

Bind postgres image from latest to v12

---

db/seeds.rb

追加されたユーザーの属性情報も、`rails db:seed`で作られるダミーデータに含めるものです。
#86 で管理画面が改修されたあと、データを見るのに便利（ないと何も表示されないのでうれしくない）です。
- Related to #86

db:seed: add user_extension

---

Gemfile
Gemfile.lock
app/assets/javascripts/decidim/admin/officializations.js.es6
app/controllers/decidim/admin/officializations/user_extensions_controller.rb
app/overrides/decidim/admin/officializations/index/user_extension_modal_override.html.erb.deface
app/overrides/decidim/admin/officializations/index/user_extension_override.html.erb.deface
app/views/decidim/admin/officializations/_show_user_extension_modal.html.erb
app/views/decidim/admin/officializations/user_extensions/show.html.erb
config/locales/ja.yml
config/routes.rb
spec/sytem/admin_officializations_user_extension_spec.rb

追加の属性を管理画面から確認するための修正です。
管理画面の参加者一覧が下のような画面になって、右端に人のアイコンが追加されます。
このアイコンをクリックすると、ダイアログが出てきます。
ダイアログの「表示」ボタンをクリックすると、追加の属性情報が表示されます。
属性情報を表示させると、線でくくったような履歴情報が登録されます（本当はその下の「メールを取得しました」のように表示ができればよいのですが、修正が難しいのでとりあえずは履歴だけ残しています）。
- Fixes #65
上記の通りです。

show user extension data in admin

---

app/views/decidim/blogs/posts/show.html.erb

「投票を支持」がoffの場合に、ブログ詳細ページのレイアウトが崩れる問題の対応。
cssで直せないかとも思いましたが、Foundationでグリッドレイアウトが組まれているようでしたので、一部の要素だけ上書きするのは影響が大きいかと思いました。
そこで、
```
<% if show_endorsements_card? %>
<div class="columns section view-side mediumlarge-4 mediumlarge-push-8 large-3 large-push-9">
```
のように 「投票を支持」がoffの際には カラム自体が表示されなかったのを
```
<div class="columns section view-side mediumlarge-4 mediumlarge-push-8 large-3 large-push-9">
　<% if show_endorsements_card? %>
```
空のカラムを表示することでレイアウト崩れを防止するようにしています。
- Fixes #107
before
after

refs #107 fix blog layout when endorsements was off

---

.cloudformation/ecr.yml
.cloudformation/staging_elasticcache.json

- 検証環境構築に使用したcloud formationを追加
- Elastic Cacheの方がjsonなのは、cloud formerで抜いたからです。。

Fix ECR & Add Staging Elastic Cache Cloud Formation

---

.ebextensions/00_options.config

- 検証環境構築の際に確認した、本番との設定の差分を取り込むためです。
- インスタイプタイプは、本番に合わせてます。
- ローカルからの、本番デプロイも問題なくできると思いますが、自信ないです。（試してないです）お手数ですが、確認お願いします。CI上からのstagingデプロイは問題なくできました。
- おそらくですが、これで設定の差分がなくなるので、 #130  で上がっていた、下記エラーも消えると思います。
>Failed Environment update activity. Reason: Configuration validation exception: RDS DB Engine Version option setting is not allowed to changed
- Related to #110

Add ElasticBeanstalk extensions config options

---

.dockerignore
.github/workflows/deploy.yml
deployments/.ebignore
deployments/.elasticbeanstalk/config.yml
deployments/Dockerrun.aws.json

- CI/CD構築のため
- コンテナ動作確認のため、一旦stagingのみ
- わざわざ一弾下げているのは、zipの転送量を最小限にするためです。また、Dockerfileがあると、そちらが優先されてしまうので。
- Related to #110, #56

Add Github workflow job for deploy to Elastic Beanstalk

---

app/controllers/concerns/decidim/needs_user_extension.rb
app/controllers/decidim_controller.rb
config/locales/ja.yml
spec/sytem/admin_officializations_user_extension_spec.rb
spec/sytem/needs_user_extension_spec.rb

#79, #134 のバグの修正として、Facebookから登録した場合など、ユーザー属性情報が登録されていない人がログインした場合、`登録されていないユーザー属性情報が見つかりました。` というメッセージを表示して、アカウント設定ページに強制的にリダイレクトさせます。
アカウント設定ページで必須項目を登録すると、通常通りにアクセスできるようになります。また、ログインしていない人も影響はありません。
なお、以下のページについてはリダイレクトさせないようにしています。
* 利用規約ページ（これは許可しないとリダイレクトループします）
* アカウント設定ページ（これも許可しないとリダイレクトループします）
* ヘルプページ（これは読めないと困りそうです）
* トップページ（これは許可しなくても良いような気もしますが、なんとなくトップページくらいは読めた方がいいかと思って許可してみました）
- Fixes #79, #134

Force to redirect account page if user_extension not found

---

.platform/nginx/nginx.conf
deployments/.platform/nginx/nginx.conf

Nginx.confのserver_tokensをoffにするために、nginx.confを追加しました。
stagingとproductionで、nginxの設定が異なるので、二つファイルを追加しています。
```
production: .platform/nginx/nginx.conf
staging: deployments/.platform/nginx/nginx.conf
```
二つの環境から`/etc/nginx/nginx.conf`にあるファイルをコピーして、`server_tokens off;`だけ追加しました。
参考: [Elastic Beanstalk Linux プラットフォームの拡張 - AWS Elastic Beanstalk](https://docs.aws.amazon.com/ja_jp/elasticbeanstalk/latest/dg/platforms-linux-extend.html)
- Related to #144

Add nginx.conf for turn off server tokens

---

config/locales/ja.yml

ログインかユーザー登録を促すメッセージで、ログインページのURLにリンクされている部分が「アカウントでログインするか、（略）」のうち「アカウント」のみだったので、「アカウントでログインする」までリンクにしてみます（Crowdinの方は修正済みです）。
また、「ユーザー」と「ユーザ」では前者の方が多いようだったので、「ユーザ登録」も「ユーザー登録」に修正しています。
#4 の修正中に気づいたのですが、直接関係はありません。

translation: fix link string to `sign_in_link`

---

config/initializers/decidim.rb

issueでは見つからなかったのですが、ダウンロードしたCSVがセミコロン区切りだった、という問題がありましたよね…？
この設定は`config/initializers/decidim.rb`の`config.default_csv_col_sep`で変更できるようだったので、カンマに修正してみます。
どこかに設定について書いておいた方がいいかもしれません（というissueを作成するといいかも？）

change Decidim settings; use `,` as default_csv_col_sep

---

config/initializers/decidim.rb

メールアドレス未確認のままログインできてしまう問題ですが、`config/initializers/decidim.rb`の`config.unconfirmed_access_for`を設定するだけでは駄目なようでした。
実際に使われる値は`Devise.allow_unconfirmed_access_for`で、アプリケーション初期化時に`Devise.allow_unconfirmed_access_for = Decidim.unconfirmed_access_for`を実行するのですが、どうも`config/initializers/decidim.rb`を実行する前にこの代入が行われてしまっている（！）ようでした。
そのため、`Decidim.unconfirmed_access_for`を設定したあと、改めて代入しなおさないと反映されない、という挙動のようです。
- Fixes #4 
この修正を反映させると、新規ユーザー登録後は未ログインの状態になって、そのままログインしようとすると、以下の画面になります。

fix login confirmation; overwrite `allow_unconfirmed_access_for`

---

app/services/user_extension_authorization_handler.rb
config/initializers/decidim_verifications.rb
decidim-user_extension/lib/decidim/user_extension/admin_engine.rb
decidim-user_extension/lib/decidim/user_extension/engine.rb

#152 のバグを修正するものです。
AuthorizationHandlerは元々提供していない（本人確認によるユーザー検証機能を提供していないため）のですが、ダミーのHandlerを実装してそれを設定するように変更しています。
（元々のエラーが出ていた原因は、管理画面用のコントローラでクラスが参照できなかったのと、handlerの名前探索に失敗していたためのようでした。）
- Fixes #152

Fix admin error

---

config/locales/ja.yml

#160 のメッセージの翻訳を修正します。
ログインと新規登録の順番は元々の（英語版等の）順番に合わせてみました。
（ただ、ローカルの開発環境ではこのメッセージをうまく有効にできてなくて確認できてないです…）
追記: #165 も合わせて対応してみます。
- Fixes #160
- Fixes #165

Fix l10n: decidim.components.add_comment_form.account_message

---

decidim-user_extension/lib/decidim/user_extension/concerns/controllers/add_user_extension_form.rb
decidim-user_extension/lib/decidim/user_extension/engine.rb

#170 について、新規登録時に現象が再現していたので、追加で修正します。
いったん入力した後は正しいエラー表示になるということだったため、新規登録画面の最初の表示の際にも空の拡張属性情報を追加するように修正したものです。
※このフォームの入力チェックはブラウザ側の(JavaScriptによる)チェックとサーバ側のチェックの両方があって、今回のものは未入力時のチェックの際にサーバ側のチェックしか行われていなかった、というものです。
- Fixes #170

Fix user registration form

---

decidim-user_extension/app/commands/concerns/decidim/user_extension/create_omniauth_commands_overrides.rb
decidim-user_extension/app/forms/concerns/decidim/user_extension/forms_definitions.rb
decidim-user_extension/lib/decidim/user_extension/concerns/controllers/omniauth_add_user_extension_form.rb
decidim-user_extension/lib/decidim/user_extension/engine.rb

Fix omniauth registration forms/commands.
Facebookログインについてはこれで修正されるのをローカルで確認しました。
- Fixes #177

Fix facebook login with UserExtension

---

Gemfile.lock

mimemagicにてライセンスの問題が見つかった影響で、古いバージョンのmimemagicが使えなくなったため、updateします。
このバージョンのmimemagicはGPL v2になっているのに注意が必要です（が、このリポジトリは公開でやっていますし、普通に運用している分には問題ないはずです）。
see: https://github.com/rails/rails/issues/41750
- Fixes #198

update mimemagic (for develop branch)

---

Gemfile
Gemfile.lock

mimemagicを0.3.10に更新します。
このバージョンでは、`freedesktop.org.xml` が適切なディレクトリに設置されている必要があります（が、現在の環境ではすでにインストールされているようです）。
- Fixes #203

update mimemagic 0.3.10

---

config/locales/ja.yml

メールの文言にある「誰かが(someone)」という日本語翻訳メッセージが不自然なので、削除します。
- Fixes #195

Fix messages in locales: remove `someone`

---

decidim-user_extension/app/commands/concerns/decidim/user_extension/destroy_commands_overrides.rb

ユーザー拡張属性を無効にした段階でユーザーを削除するとエラーになる件を修正します

Fix an error when destorying user without user_extension

---

app/helpers/decidim/paginate_helper.rb

(We should remove the fix when upgrade Decidim 0.24.0.)
#219 を修正するため、`Decidim::PaginateHelper` だけ最新版から持ってきました。
- Fixes #219

Backport Decidim::PaginateHelper from v0.24.0

---

app/views/decidim/application/_collection.html.erb

#192 の対応で、とりあえずドキュメント数の表示を正しくするべく最新のテンプレートファイルを持ってきたものです。
関連画像の表示は変更していません。
元ファイルは以下になります。
* decidim-core/app/views/decidim/application/_collection.html.erb
- Related to #192

ドキュメント数の表示のみを修正（関連画像は現状のまま）

---

.cloudformation/cloud_formation.yml

パフォーマンス向上・負荷軽減のために、静的ファイルをキャッシュするためのcloud frontを生成するコードの追加
stagingのcloud formationのスタック: staging-decidim-app-cloud-front
- Related to #185 
- Fixes #?

パフォーマンス向上・負荷軽減のためcloud frontのcloud formationを追加

---

config/sidekiq.yml

sidekiqのワーカー数が、pumaのワーカー数5よりも多い。
かなり余裕があり、メモリ効率も良くないのでパフォーマンス観点で減らした。
これでも、本番はサーバーが現状3-5台なので、最大9-15が同時実行数となる。
- Related to #185 
- Fixes #?

chore: decrease sidekiq worker 6 -> 3

---

.cloudformation/ecr.yml

CI/CDを作成した際にタグの打ち方が変わったので、それに合わせて古いイメージを削除する設定を追加した。
下記のプレフィックスから始まるタグのイメージは7つのみ保持する。それ以上削除する設定とした。
- staging-
- production-
> imageCountMoreThan では、イメージは期間の新しいものから始めて最も古いものへと pushed_at_time に基づいて順に並べられた後、指定したカウントより大きいイメージはすべて期限切れとなります。
https://docs.aws.amazon.com/ja_jp/AmazonECR/latest/userguide/LifecyclePolicies.html
既にcloud formationには反映済み
[対象のstack](https://ap-northeast-1.console.aws.amazon.com/cloudformation/home?region=ap-northeast-1#/stacks/stackinfo?stackId=arn%3Aaws%3Acloudformation%3Aap-northeast-1%3A887442827229%3Astack%2Fdecidim-cfj-ecr-repository%2F5bd60330-9806-11eb-92aa-06c3336b4a0d&filteringStatus=active&filteringText=&viewNested=true&hideStacks=false)
- Related to #56

chore: update ecr lifecycle policy to expire old tag

---

deployments/staging/00_options.config

プラットフォームバージョンが定期的に上がっているが、気づいたベースで手作業で更新している。
マネージドプラットフォーム更新を有効化することで、手作業が不要になる。
マイナー更新のみstaging環境なので問題無い。定期的にみて問題がなければ、本番に取り込む手助けにもなる。
自動メンテナンス時間はUTC  "Mon:00:00"
日本時間月曜日朝3時
https://docs.aws.amazon.com/ja_jp/elasticbeanstalk/latest/dg/command-options-general.html#command-options-general-elasticbeanstalkmanagedactions
- Related to #241

chore: enabled auto eb platform update on staging

---

deployments/staging/00_options.config

コスト削減のためstaging環境で、Spotインスタンスの有効化
- Fixes #?

chore: enabled spot instance on staging environment

---

CHANGELOG.md

release v0.23.0-2021-06-22 のCHANGELOGのupdate

update CHANGELOG v0.23.0-2021-06-22

---

deployments/.ebextensions/02_common_options.config

アクセス等のCPUの負荷増により、オートスケーリングの設定がかみ合わなくなってきた。
そのため、最大から平均に変更する。
- Related to #264

chore: change auto scale trigger to Average from Maximum

---

config/locales/ja.yml

ディベート終了時のメールで訳文抜けが出るので、追加します。
- Fixes #268

Fix #268; add locale for debate_closed

---

config/environments/production.rb

日本語のlocaleファイルの抜けがあった場合に、production環境では英語にfallbackするようにする修正です。
探索順序は以下になるはずです。
* 設定が日本語だった場合: まず日本語で探して、見つからなければ英語で探す
* 設定が英語だった場合: まず英語で探して、見つからなければ日本語で探す
* 設定がそれ以外だった場合: まずそのロケールで探して、見つからなければ日本語で探して、それでも見つからなければ英語で探す
日本語でも英語でもない場合は、missing: xxxといった表示になるのは現状と同じです。

Fix fallbacks of i18n; use both :ja and :en

---

deployments/docker-compose.yml
deployments/etc/nginx/conf.d/default.conf
docker-compose.yml

デプロイ時に、public配下をdocker volumeで共有する機構の削除。インスタンスが更新されない場合、public配下が更新されないケースがあるため。
Cloud Front導入もある。それを踏まえキャッシュはそちらに全て寄せて、nginxではコンテンツを持たないようにした。
- Fixes #274

fix: delete public docker volume for cache

---

.cloudformation/cloud_front.yml
docs/INFRA.md

本番環境のcloud frontを作成するにあたり、依存するcache policyが環境ごとに作られるように修正しました。
また一定期間後に、ログのストレージタイプを変更するライフサイクルを設定しました。
- Related to #185

fix: change cache policy name to by environment

---

.cloudformation/waf.yml
docs/INFRA.md

セキュリティ向上のため、カウントモードでwafを追加する
ルールは、オーソドックスな下記5つ
- AWSManagedRulesCommonRuleSet
- AWSManagedRulesKnownBadInputsRuleSet
- AWSManagedRulesAmazonIpReputationList
- AWSManagedRulesLinuxRuleSet
- AWSManagedRulesSQLiRuleSet
https://docs.aws.amazon.com/ja_jp/waf/latest/developerguide/aws-managed-rule-groups-list.html
- Related to #180

chore: add cloud formation of waf

---

.cloudformation/cloud_front.yml

cloud frontのログバケットに対して、athenaのテーブルを作成した。
Glacierに移行してしまうとスキャン対象外になる。そのため90日後にGlacierに移動するライフサイクルを削除した
- Related to #185

chore: remove glacier life cycle on cloud front log s3

---

app/helpers/decidim/resource_versions_helper.rb

ディベートのコメント一覧画面において、`versions` テーブルに対する不要な（重い）クエリを発行しないようにするための修正です。
ディベートのコメント一覧画面ではversionsテーブルは件数しか使用していないのですが、現状`SELECT "versions".* FROM "versions" WHERE ...`というクエリを発行するようになっています。そのため、これを`SELECT count(*) ...`にするものです。
ちなみに現状は上記クエリを発行した直後で `SELECT count(*) ...` を再度発行するのですが、2回目以降はキャッシュが使われる（のでDBアクセスそのものが1回分省ける）ようでした。

`Decidim::ResourceVersionsHelper.resource_version` でのクエリを最適化する

---

config/locales/ja.yml

#59 の修正として画像アップロードの文言を修正します。
- Fixes #59
)

画像のファイルサイズではなく画像の縦横サイズの文言も追加

---

decidim-comments/app/queries/decidim/comments/sorted_comments.rb

`undefined method `limit' for#<Array:XXXX>`といったエラーが出るようなので確認してみたところ、scopeの結果がArrayになっていることがあるようだったため、その場合は`Enumerable#take`を使うように修正してみました。

Fix limit for Decidim::Comments::SortedCommments

---

config/locales/endorse_ja.yml

#281 に関連して、「endorsement」に当たる日本語を「オススメ」に変更するためのYAMLファイルを作ってみました。
作業の都合で`config/locale/ja.yml`と別ファイルになってしまっています（混ぜるべきかどうかはちょっと迷いがあります）。
- Related to #281
例えば↓こんな感じになります。

Fix messages `endorsement` in JA; use `オススメ`

---

db/seeds.rb

#304 の修正で、`rails db:seed`が(少なくともmacOSでは)正常に動作するようにします。
DecidimAwesomeで追加されているmapとiframeのseedは（なくても特に困らないため）作らないようにしています。
- Fixes #304

Fix #304; ignore seeds of DecidimAwesome

---

config/initializers/fileutils.rb
lib/monkey_patching_fileutils.rb

This patch is from https://github.com/docker/for-linux/issues/1015#issuecomment-811453779
DockerでFileUtilsのcopy_fileを使うと0バイトのファイルができることがある（！？）ようなので、それをtouchで回避するworkaroundを入れてみます。
touchでファイルがなければ作るだけなので、Docker以外でも特に問題はないはずです。
- Fixes #253 , #302

Fix db:seed in docker

---

deployments/production-v0-23-5/00_options.config
deployments/staging/00_options.config

Cloud Watch のアプリケーションログ保持期間を延長した
- 本番 7日-> 30日
- staging 3日 -> 14日
- Fixes #307

Cloud Watch のアプリケーションログ保持期間の延長

---

.cloudformation/waf.yml

カウントモードでログ収集していたAWSManagedRulesCommonRuleSet を有効化します。
3週間分のログを分析した結果、日本から一定リクエストがあり、誤検知が疑われるルールが3つありました。よって下記をブロック対象から除外しました。
- CrossSiteScripting_BODY
- 管理画面でhtmlをおくってる箇所でひっかる
- SizeRestrictions_BODY
- 時々話題になるrule展でリクエストが大きなってる箇所がひっかる
- GenericRFI_BODY
- 管理画面ぽい
https://docs.aws.amazon.com/ja_jp/waf/latest/developerguide/aws-managed-rule-groups-list.html
WAFをログに落としている箇所で、cookieが落ちていたので削除するように修正しました。ログから消すことでファイルサイズの圧縮が期待できます。基本的にcookieは調査には不要です。
- Related to #180

chore: enabled AWSManagedRulesCommonRuleSet on AWS WAF

---

app/uploaders/decidim/application_uploader.rb

#323 の対応で、`Decidim::ApplicationUploader#validate_inside_organization`を本家の定義に戻します。
- Related to #323

Reset `Decidim::ApplicationUploader#validate_inside_organization` to original definition

---

.cloudformation/cloud_front.yml
app/uploaders/decidim/application_uploader.rb

#317 で修正したcloud formationと、url関数の修正
Staging 環境で動かした場合に、Origin Pathが邪魔して読み込めないものがあった。
また、decidimのデフォルトアイコンが表示されないため修正
- Fixes #317

fix url & remove OriginPath

---

app/controllers/concerns/decidim/proposals/cookie_orderable.rb
config/initializers/decidim_override.rb

提案コンポーネントのユーザー用一覧画面でのソート順をクッキーに保存できるようにします。

Add CookieOrderable; store proposals orders in cookies

---

decidim-user_extension/app/views/decidim/devise/registrations/_user_extension.html.erb
decidim-user_extension/config/locales/ja.yml

#333 の対応として、誕生年の入力欄に説明と例を追加し、inputmodeとmaxlengthによる入力制限を追加しました。
合わせて名前と住所の入力欄にもautocompleteを追加して補完されやすくしています。
- Fixes #333

生年や名前等の入力フォームを改善（入力制限・入力支援を追加）

---

app/assets/stylesheets/comment_content.scss

#288 に対応するためのCSSの修正で、適切に改行するようにします。
どこまで設定するかは要検討ではありますが、とりあえずdeicidim-commentsのコメント本文のクラスのみ適用しています。
- Fixes #288

長いコメント（アルファベット等）を適切に改行させる

---

config/routes.rb

wwwのトップページに来た場合のみ、https://meta.diycities.jp/ にリダイレクトさせるようにしてみます。
なし

Redirect https://www.diycities.jp/ to Metadecidim Japan

---

config/database.yml
docs/DEVELOPMENT.md

開発時の都合でDB名も変更したい場合に、hostやportと同様に環境変数で上書き設定できるようにする修正です。
何もしなければこれまでと同様に`decidim-app_development`と`decidim-app_test`になります。
合わせてDEVELOPMENT.mdにhost等も含めて変更方法を書いておきました。

Allow to change DB name in dev/test

---

.cloudformation/waf.yml

画像アップロード時に誤検知されることがあるので、WAFのルールでSQLi_BODYを無効化します。
staging, production反映済みです。
- Fixes #336

chore: disabled SQLi_BODY rule on waf for uploading image

---

config/locales/ja.yml

`Is visible`(が非表示になっていた件)と`duplicate`(が訳されてなかった件)の翻訳について、crowdinには反映済みですが、現状のバージョンでも対応されるよう修正しておきます。
- Related to #344

Fix translation: `Is visible` `duplicate`

---

app/assets/stylesheets/search.scss
config/routes.rb

日本語での検索が機能しないので、いったん検索機能を見えなくします。
* 検索窓をCSSで見えなくする
* `/search`に直接アクセスされた場合はトップページにリダイレクトする
根本解決はまた別途頑張ります…。
- Related to #31
ローカルの開発環境だと以下のようになります。

Remove search box

---

.github/workflows/deploy.yml
deployments/production-v0-24-3/00_env_options.config
deployments/production-v0-24-3/00_options.config

decidim v0-24-3のデプロイ時に環境を切り替えのたのでそれに追従するための変更
- Related to #151

update production environment name

---

app/controllers/decidim/debates/versions_controller.rb
config/locales/en.yml
config/locales/ja.yml
docs/UPGRADE.md
spec/sytem/needs_user_extension_spec.rb

ディベートで履歴が大きすぎる場合にサーバに負荷がかかるようなので、差分の大きさについて適当な上限を設けて、それを超える場合は表示をあきらめるようにしてみました。
とりあえず現状は1MBに指定してみています(`OBJECT_CHANGE_SIZE_LIMIT`の定数の値です)。
* DBの操作を頑張ればクエリを発行してデータを受け取る前にチェックできそうですが、クエリ以上に画面描画にかかるコストが大きいようなので、DBクエリそのものは変更せずに通常通りデータを受け取った後、そのサイズを見て描画を行わないようにする修正になっています。これでもダメそうであれば、DBクエリの方を修正します。
* 現状はディベートが問題になっているのでそこだけ修正していますが、同様の履歴機能は、アカウンタビリティ・イニシアティブ・ミーティング・提案それぞれに存在しています。そちらは対応していません（それぞれ個別に同様のコードを追加する必要があります）。
↓こんな感じのエラーメッセージを出して履歴の一覧画面に戻します。

履歴が大きすぎる場合に表示させないよう修正

---

.github/workflows/rails-test.yml

テストの実行結果ログが見えにくかったため、GitHub Actionsのrails-testを整理します。
bundle installは`bundler-cache: true`では不要だそうなので削除するのと、環境変数を個別のstep内で指定するのではなくjob全体で共有するように修正しています。

Fix GitHub Actions: move env, no need bundler

---

app/models/decidim/user_base_entity.rb

`scope.filter(&:visible?)`の実行時にエラーが出ることがあるので、エラーが出ないフィルタリングだけを使って絞り込みを行うよう修正します。
根本的な解決はv0.25.xに上げた方が良さそうではあります…。

Fix `undefined local variable or method component` error

---

Gemfile
Gemfile.lock
db/migrate/20220324111735_create_decidim_term_customizer_translation_sets.decidim_term_customizer.rb
db/migrate/20220324111736_create_decidim_term_customizer_translations.decidim_term_customizer.rb
db/migrate/20220324111737_create_decidim_term_customizer_constraints.decidim_term_customizer.rb
db/schema.rb

#354 のためのブランチで、v0.24ブランチにDecidim::TermCustomerを追加してみます。
- Related to #354
↑これはブラウザで編集するための管理画面ですが、CSV等でエクスポート＆インポートもできます。
↑また、「まとめて追加」機能を使うと、文字列検索から候補を個別に追加できるので、かなり便利そうです（抽出はできるんですが一括置換はできないため、抽出した後はCSVにエクスポートしてエディタやExcelで編集するのが賢明そうです）。

Add Decidim::TermCustomer

---

app/commands/decidim/verifications/authorize_user.rb
app/controllers/decidim/verifications/authorizations_controller.rb
spec/commands/decidim/verifications/authorize_user_spec.rb

Backport https://github.com/decidim/decidim/pull/8940
上記の本家PR(v0.26用)での修正をこちらに適用してみます。
（なおテスト用のspec/commands/decidim/verifications/authorize_user_spec.rbには、`class DummyAuthorizationHandler` のコードをまるごと同梱させています。）
- Related to https://cfj.slack.com/archives/C01CT4GTEBU/p1649825981863759

Fix AuthorizeUser; "Fix verification report with multitenants"

---

Gemfile
Gemfile.lock

TermCustomizerの参照リポジトリをcodeforjapanのforkに差し替えます。
リポジトリの中身自体は現状では同一なので、挙動の変更は特にないはずです。
- Related to #354

Fix repository of decidim-module-term_customizer

---

Gemfile.lock
decidim-user_extension/decidim-user_extension.gemspec

`Decidim::UserExtension`の依存にRailsのバージョンを含めないようにします。
テスト等の特殊な環境以外では（Decidimで使っているRailsをそのまま使うはずなので）特に問題ないかと思います。
- Related to #373

decidim-user_extension: Remove Rails version

---

.github/workflows/lint.yml
.github/workflows/rails-test.yml

RuboCopを同じAction内で動かす必要はないので、分割しておきます。

GitHub Actions: RuboCop should be another action

---

app/assets/javascripts/decidim/decidim_awesome/editors/quill_editor.js.es6

Apply fix of legacy_quill_editor.js.es6 to quill_editor.js.es6
#377 の対応のため、 https://github.com/codeforjapan/decidim-cfj/blob/develop/app/assets/javascripts/decidim/decidim_awesome/editors/legacy_quill_editor.js.es6 と同等の修正を `quill_editor.js.es6` に対して上書き適用されるよう、同名のファイルを追加しています。
- Fixes #377

Fix quill-html-edit-button (#377)

---

lib/tasks/download.rake

引数のidを使うように修正。
timezoneをorganizationから取得

fix: use arg id & timezone

---

lib/tasks/download.rake

`download:user`の最適化をするもので、結果は変わらないことが期待されてます。
主にN+1クエリを回避するのが目的で、それ以外の修正も一部追加しています。
- Related to #382

Optimize `download:user` task

---

config/initializers/decidim.rb

#378 の件ですが、どうもavailable_localesの順番に依存してseedのデータを作るようで、一番うしろになっているのが問題なようです。
というわけで、日本語と英語の順番を入れ替えて、日本語を先頭に移動させます。
- Fixes #378

Fix locale order to generate seeds in JA

---

config/locales/ja.yml
decidim-user_extension/config/locales/ja.yml

イニシアチブ用の翻訳も少し追加します。
- Related to #387

Add some locale entries for initiative

---

config/secrets.yml

defaultの設定でLINEログインがONになっていたので、OFFに変更します。

LINE login: default is `false`

---

decidim-comments/app/controllers/decidim/comments/comments_controller.rb
decidim-comments/lib/decidim/comments/comments_helper.rb
spec/factories.rb
spec/sytem/comment_sort_spec.rb

#407 の対応のため、`comment_default_order`というクッキーを追加します。
----
Decidimのコメント機能は、提案コンポーネントやディベートコンポーネント、予算コンポーネントなどの各画面にコメントを追加するもので、以下のような特徴があります。
* 様々なコンポーネントにコメント機能を追加できる
* コメントはcommentIdを持っている
* コメントに対するコメントも書ける。これはスレッドとして表示される
コメント表示は対象となるコンポーネントのアイテムを表示する際に合わせて表示されることもあれば、コメント単独で表示することもできます。
ある記事（例えば提案コンポーネントであれば「ある提案」）に対してのコメントは、その記事のURLにアクセスすると表示されます。
* https://meta.diycities.jp/assemblies/nazo/f/286/proposals/321#comments-for-Proposal-321
* https://meta.diycities.jp/assemblies/nazo/f/286/proposals/321
commentIdを指定すると、指定されたcommentIdのコメントと、それにぶら下がる一連のコメントが表示されます。ぶら下がるコメントがない場合は、単独のコメントのみ表示されます。
* https://meta.diycities.jp/assemblies/nazo/f/286/proposals/321?commentId=6893#comment_6893
* https://meta.diycities.jp/assemblies/nazo/f/286/proposals/321?commentId=6894#comment_6894
* …

Add a cookie param for comment order

---

lib/tasks/replace_to_null.rake

decidim_organizationsテーブルで""文字が入ってるカラムがエラーを起こしているのでnullに書き換えるコマンドの追加です
- Fixes #?

feat: add replace to null decidim_organization command

---

docs/UPGRADE.md

`docs/UPGRADE.md` で、パスが変更になったファイルがあったので修正しておきます。
- Fixes #?

Fix paths in UPGRADE.md

---

.github/workflows/rails-test.yml

GitHub Actionsで使っている `actions/checkout` と `actions/setup-node` は新しいバージョンがリリースされていたので更新しておきます。

Update `actions/checkout` and `actions/setup-node`

---

config/initializers/decidim.rb

#446 の修正で、`max_complexity`を変更するタイミングをinitializerの実行後に行うようにします。
- Fixes #446

Fix #446; set `max_complexity` after initializers

---

config/locales/ja.yml

#225 の対応で、censusを `国勢調査` ではなく `センサス` にします。
crowdinの方はすでに修正済みです（が、decidim本家の翻訳は更新されていなさそう…）
- Fixes #225

locale: fix term `census`

---

app/uploaders/decidim/image_uploader.rb

画像のuploadの制限を緩くします
とりあえずはヒーロー画像と同じサイズまでは許容するように変更しました
- Fixes #?

refactor: change image upload size limit

---

lib/tasks/comment.rake

#454 で追加したタスクですが、CommentVoteも合わせて消せるよう修正してみました。これでどうでしょうか？
合わせて正常にアクセスできたときにはログを残さないようにしてみました。
- Related to #454

Fix comment_vote dependency

---

config/initializers/slack.rb
config/puma.rb
lib/slack_chat_messenger.rb

現状では`SlackChatMessenger`はconfig/puma.rb内でしか使えないので、Decidim本体の好きなところから使えるようにlibに置くようにします。
config/puma.rb内でもrequire_relativeで読み込んでいるので、今まで通り使えます。

refactor: Move SlackChatMessenger to use in Decidim apps

---

config/locales/ja.yml

古い文言が残っていたので削除します。
これで「支持済み」が「オススメ済み」になります。

Fix old message for endorsement button

---

app/packs/src/decidim/decidim_awesome/editors/editor.js
app/packs/stylesheets/decidim/admin/application.scss
app/packs/stylesheets/decidim/cfj/ql_html_editor.scss
app/packs/stylesheets/decidim/decidim_application.scss

Quill EditorのHTMLボタン拡張について、JSファイル内でCSSを設定していた部分について、普通のCSSファイルに切り出してみます。見た目は変更ないはずです。
この拡張のJS部分についても後でもう少し整理したいと思っています（現状はdecidim_awesomeのファイルと混ざってしまっていて良くないので…）。

refactor: move CSS from editor.js

---

config/locales/ja.yml

#36 の対応です。
`お楽しみください！`は`decidim.messaging.conversation_mailer.*.outro`というキーの値だったようなので、まとめて削除してみました。
合わせて「Hi, ○○○!」のところも「○○○さん、こんにちは。」に修正してみました。
- Fixes #36

`outro` in messaging should be empty

---

app/commands/decidim/accountability/destroy_all_results.rb
app/commands/decidim/areas/destroy_all_areas.rb
app/commands/decidim/assemblies/destroy_all_assemblies.rb
app/commands/decidim/blogs/destroy_all_posts.rb
app/commands/decidim/budgets/destroy_all_budgets.rb
app/commands/decidim/comments/destroy_all_comments.rb
app/commands/decidim/debates/destroy_all_debates.rb
app/commands/decidim/destroy_all_attachments.rb
app/commands/decidim/gamifications/destroy_all_badges.rb
app/commands/decidim/meetings/destroy_all_meetings.rb
app/commands/decidim/messaging/destroy_all_messages.rb
app/commands/decidim/organizations/destroy_organization.rb
app/commands/decidim/pages/destroy_all_pages.rb
app/commands/decidim/participatory_processes/destroy_all_participatory_processes.rb
app/commands/decidim/proposals/destroy_all_proposals.rb
app/commands/decidim/surveys/destroy_all_surveys.rb
lib/tasks/delete.rake

指定したorganizationのコメントその他をまとめて削除するタスクを追加します。
安全側に倒して個別に削除しているためそれなりの時間がかかるかもです。
rakeタスクとして`delete:destroy_all`を指定します。
その際、削除対象のorganizationの名前を`DECIDIM_ORGANIZATION_NAME`で指定します。何も指定しない場合、組織が存在しない場合はエラーが出て終了します。
```console
DECIDIM_ORGANIZATION_NAME="組織名" bin/rails delete:destroy_all
```
- Fixes #?

Add task `delete:destroy_all`

---

config/locales/ja.yml

コメントのソート順と提案のソート順について、並び順の名前に統一感がなかったため変えてみます。

提案とコメントの並び順の項目名を変更

---

config/initializers/decidim_override.rb

DynamicMapの地図を表示する際、マーカーが表示されないことがあるのを修正します。
問題を起こす挙動というか最終的な原因自体はあまり把握できていないのですが、マーカーの情報として緯度・経度が空（nil or NaN）の値が渡ってくる場合があるようで、その場合に問題が生じるようでした。
そのため、`Decidim::Map::DynamicMap::Builder#map_element`でそういったデータが含まれていた場合、除去する処理を加えています。

Fix markers in dynamic_map

---

docs/DEVELOPMENT.md

DEVELOPMENT.mdにあるdocker-composeを試してみたところ、db:seedを実行するところで下記のようなエラーが出たのでdb:resetする流れを追記してみます。
```
rails aborted!
ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_decidim_users_on_nickame_and_decidim_organization_id"
DETAIL:  Key (nickname, decidim_organization_id)=(foster, 1) already exists.
```
（本家のseedの書き方が問題ありそう…）

docs: db:reset when db:seed failed

---

.github/workflows/rails-test.yml

GitHub Actionsでimagemagick7のビルドをするのはかなり時間がかかっているため、imagemagickの公式サイトからダウンロードしたバイナリを使うように修正し、実行時間短縮を図ります。
バイナリはポータブルに実行できるAppImageなので、 `vendor/imagemagick7/bin` にそのまま置いてあります（convertにrenameしてあります）。バージョンは `Version: ImageMagick 7.1.1-6 Q16-HDRI x86_64 1be141ef8:20230402` です。
また、aptでlibfuse2を追加しています。

GA: Use imagemagick7 in local binary

---

Gemfile
Gemfile.lock
babel.config.json
config/locales/polis_ja.yml
db/migrate/20230426065808_add_polis_site_id_to_organizations.decidim_polis.rb
db/migrate/20230426065809_add_polis_site_url_to_organizations.decidim_polis.rb

Decidim上でPol.isが使えるようになるdecidim-polisを追加してみました。
オリジナルではいろいろ動かなかったので、forkしてhttps://github.com/takahashim/decidim-polis.git を使っています。
管理者画面の組織の設定画面でpol.isの設定ページが追加されます。
コンポーネントとしてPol.isが追加できるようになります。
設定すると、ユーザー画面で表示できるようになります。
ログインしていない場合は、回答はできずに図の表示だけされます。

Add decidim-polis

---

Gemfile.lock

`Decidim::Polis::PolisHelper.avatar_url`がエラーになることがあるようなので修正します。

Update decidim-polis to fix avatar_url

---

spec/system/comment_sort_spec.rb

テストが失敗するようになっていたので、修正します。
メッセージのテキストが日本語になっていたようなので、それに合わせてテストも修正します。
- Fixes #?

Fix spec: use japanese texts

---

Gemfile.lock
config/locales/polis_ja.yml
db/migrate/20230522090010_remove_polis_site_id_and_url.decidim_polis.rb
db/schema.rb

元々のdecidim-polisではorganizationにpol.isのsite_idを持たせていたため、組織内では複数のpol.isコンポーネントを作っても同じ画面しか表示できませんでした。
そのため、コンポーネントのsettingsにsite_id（とsite_url）を保持するように変更します。
（decidim-polis自体は変更済みで、変更したリビジョンを使用するように変更するものです）
- Fixes #?

1組織内で複数のpol.isをサポートするよう修正

---

app/cells/decidim/amendable/amend_button_card_cell.rb
config/locales/ja.yml

「提案を修正」のところの翻訳がされていないようだったので、翻訳されるよう修正します。
`Decidim::Amendable::AmendButtonCardCell#new_amend_help_text`をoverrideするだけではあるのですが、そこだけ修正するのはうまくいかなかったので、ファイルまるごと上書きして修正しています。
- Fixes #?

Fix amendable_fields in `Decidim::Amendable::AmendButtonCardCell`

---

config/locales/en.yml

#541 の修正で、英語のlocaleデータを追加します。
ただ、これだと元々の英語版での表示とは若干異なってしまっていて、単語（titleとbody）がcapitalizeされるのでした。
（これはデータを修正すればいいのですが、他の単語はふつうCapitalizeしたデータになっているので、ここだけ変えるのもどうかという気がしています…）
- Fixes #541

Fix amendable_fieds in English; Add locale text in English

---

app/views/decidim/blogs/posts/show.html.erb
config/initializers/decidim.rb

<del>注意) これは #549 がマージされた前提のPRで、 #549 との差分になっています。</del>
→ #549 がマージされたので develop との差分になりました
- ブログエントリの本文が長い場合、metaとOGPのdescriptionはtruncateします
- ブログエントリに画像が含まれる場合、その画像をmetaとOGP画像に使用します
前者のtrucateする長さは環境変数 `DECIDIM_BLOG_OGP_DESCRIPTION_LIMIT`で指定できます。指定されていない場合のデフォルトは150文字にしています。
- Fixes #?

ブログのmeta・OGPを修正

---

docs/DEVELOPMENT.md

Compose V2に合わせて、ドキュメントにあるCLIで使う`docker-compose`を`docker compose`に置き換えます。
ローカルの開発環境で使う分には問題なさそうでした。
https://docs.docker.com/compose/migrate/

Use `docker compose` instead of `docker-compose`

---

docs/INFRA.md

ドキュメントの文言修正です。
Cloud FormationになっていたところをCDKにします。

docs: Replace CDK instead of Cloud Formation

---

app/controllers/decidim/debates/versions_controller.rb

だいぶ古い修正のミスのようですが、Decidim::Debates::VersionsControllerのスーパークラスを間違っていたようなので再度修正します。
- Related to #359

Fix controller name

---

app/forms/decidim/debates/close_debate_form.rb

Decidim::Debates::CloseDebateForm がv0.27.4で更新されていたので、差分を反映させます。
- Related to #415

Update a form in v0.27.4

---

decidim-comments/decidim-comments.gemspec
decidim-comments/spec/commands/create_comment_spec.rb
decidim-comments/spec/controllers/decidim/comments/comments_controller_spec.rb
decidim-comments/spec/events/decidim/comments/comment_by_followed_user_group_event_spec.rb
decidim-comments/spec/events/decidim/comments/user_group_mentioned_event_spec.rb
decidim-comments/spec/events/decidim/comments/user_mentioned_event_spec.rb
decidim-comments/spec/forms/comment_form_spec.rb
decidim-comments/spec/helpers/comments_helper_spec.rb
decidim-comments/spec/lib/decidim/comments/comment_serializer_spec.rb
decidim-comments/spec/lib/decidim/comments/comment_vote_serializer_spec.rb
decidim-comments/spec/lib/decidim/comments/export_spec.rb
decidim-comments/spec/models/comment_spec.rb
decidim-comments/spec/models/seed_spec.rb
decidim-comments/spec/permissions/decidim/comments/permissions_spec.rb
decidim-comments/spec/queries/sorted_comments_spec.rb
decidim-comments/spec/services/decidim/comments/comment_creation_spec.rb
decidim-comments/spec/system/admin_manages_comments_spec.rb
decidim-comments/spec/system/search_comments_spec.rb
decidim-comments/spec/types/comment_mutation_type_spec.rb
decidim-comments/spec/types/comment_type_spec.rb

decidim-commentsについて、v0.27.4との差分を反映させます。
ざっと見たところ、変更がありそうなのはgemspec（Rubyのバージョン）とテストだけのようでした。
- Fixes #?

Update decidim-comments v0.27.4

---

config/initializers/decidim.rb
config/puma.rb
config/secrets.yml

提案で、住所の入力が表示されない問題の修正
static providerをglobalのproviderとして使わないようにしました。
- Fixes #?

refactor: fix map provider params

---

config/locales/ja.yml

日本語選択時の日付の表記を変更します。
ただし、#564 の日にちだけ独立して表示されるものには「日」はつきません…(formatが直接テンプレートに埋め込まれていました…)
- Fixes #564

Fix some Date and Time formats in JA

---

app/presenters/decidim/notification_to_mailer_presenter.rb
spec/presenters/decidim/notification_to_mailer_presenter_spec.rb

ダイジェストメールの日時をorganizationのタイムゾーンに合わせるようにします。
- Fixes #?

Decidim::NotificationToMailerPresenter: support organization's locale

---

public/robots.txt

sitemap.xmlがエラーになる件ですが、とりいそぎクローラから辿れなくするものです。
- Fixes #?

Disallow sitemap.xml

---

config/locales/ja.yml

`Last activity`の訳語を「最近のアクティビティ」に変更します。
変更する箇所は以下の3か所になります：
* トップページのlast_activityコンテンツブロックのタイトル (content_blocks.last_activity.title)
* 上記のコンテンツブロック内の「すべて表示」ボタンを押した先のページのタイトル (last_activities.index.last_activity)
* 管理画面で表示されるlast_activityコンテンツブロックの名前 (content_blocks.last_activity.name)
- Fixes #?
トップページ（PR適用後）：
/last_activities ：
管理画面（設定→ホームページ）：

Fix translation of `last_activity`

---

docs/UPGRADE.md
spec/rails_helper.rb
spec/system/admin_officializations_user_extension_spec.rb
spec/system/comment_sort_spec.rb
spec/system/needs_user_extension_spec.rb
spec/system/user_profile_spec.rb

#584 でいったん回避したテストを修正します。
`"--headless=new"`というオプションを追加しています。
- Related to #584

fix: options of Capybara driver

---

Gemfile
Gemfile.lock
db/migrate/20240128143437_create_decidim_navigation_maps_blueprints.decidim_navigation_maps.rb
db/migrate/20240128143438_add_title_to_navigation_maps_blueprints.decidim_navigation_maps.rb
db/migrate/20240128143439_create_decidim_navigation_maps_blueprint_areas.decidim_navigation_maps.rb
db/migrate/20240128143440_add_link_type_to_decidim_navigation_maps_blueprint_areas.decidim_navigation_maps.rb
db/migrate/20240128143441_add_area_id_to_decidim_navigation_maps_blueprint_areas.decidim_navigation_maps.rb
db/migrate/20240128143442_add_color_to_navigation_maps_blueprint_areas.decidim_navigation_maps.rb
db/migrate/20240128143443_add_reference_to_content_block_to_blueprints_table.decidim_navigation_maps.rb
db/migrate/20240128143444_add_height_to_navigation_maps_blueprints.decidim_navigation_maps.rb
db/schema.rb
package.json
yarn.lock

decidim-navigation-mapsの追加対応
- Fixes #?

feat: add decidim-navigation-maps

---

db/migrate/20200912130614_fix_reference_for_all_resources.decidim.rb

どうもmigrationファイルに修正が入っていたようで、これがないとエラーになる場合があるため今更ながら対応するものです。
本家では https://github.com/decidim/decidim/blob/develop/decidim-core/db/migrate/20180206143340_fix_reference_for_all_resources.rb のファイルになります。
- Fixes #?

Fix a migration file

---

spec/system/user_profile_spec.rb

直接spec_helper.rbを呼ばずにrails_helper.rbを呼ぶよう修正します（そうしないと個別にテストを実行できないため）。

fix to allow system specs to be run for each file

---

config/application.rb
config/sidekiq.yml

config.load_defaultsを6.0まで上げます。
最終的には6.1まで上げた方が良さそうですが、もろもろ設定が変更されるので小さく修正するようにしていまｓ．
また、`config.action_dispatch.use_cookies_with_metadata`の変更は不可逆なため、いったん変更しないようにしておきます。
この修正が問題ないようであれば、別途`config.action_dispatch.use_cookies_with_metadata`を変更する予定です。
- Fixes #?

fix: update load_defaults to `6.0`

---

config/application.rb

#605 でいったん無効化していた`use_cookies_with_metadata`を有効にします。
この変更により、クッキーへの格納方法が変わるため、それ以前のバージョンに戻すとクッキーがおかしくなるため注意してください。
それ以外の挙動には変更はないはずです。
- Related to #606

fix: make use_cookies_with_metadata true (same as default)

---

config/application.rb

( #608 が先にmainにマージされる前提で作ったPRのため、target branchがそちらになっています。）
#606 の一環で、 #605 に引き続き、config.load_defaultsを6.1まで上げます。
`config.action_dispatch.cookies_same_site_protection`と`config.action_controller.urlsafe_csrf_tokens`は変更しないようにしています。
この2つの中では、`urlsafe_csrf_tokens`を先に有効化した方がよいかもしれません。
→確認したところ `cookies_same_site_protection` はDecidim本体のdecidim-coreで設定されていたため、`config.action_controller.urlsafe_csrf_tokens`のみ設定を残しています。
- Related to #606

fix: update load_defaults to `6.1`

---

config/initializers/decidim_override.rb

#612 を修正するため、`@transliterators`の`:ja`に何も変換しないProcを渡すように修正します。
本来は`:en`は修正しなくてもいいはずですが、ダミーのデータで試す際にはlocaleの判別がうまくいってない場合があったため、念の為こちらも修正してみます。
- Fixes #612

Fix `I18n.transliterate`

---

config/application.rb

#609 でいったん無効化していた`urlsafe_csrf_tokens`を有効にします。これで #606 の対応は完了し、6.1のデフォルト設定になります。
この変更により、CSRF対策用のhidden文字列のエンコード方法が変わります。が、切替時にフォームを表示している以外はエラーにならないと思われます。
それ以外の挙動には変更はないはずです。
- Related to #606

fix: remove `urlsafe_csrf_tokens`

---

.github/workflows/_check.yaml
app/models/decidim/searchable_resource.rb
app/packs/stylesheets/decidim/cfj/search.scss
app/packs/stylesheets/decidim/decidim_application.scss
config/initializers/pg_search_override.rb
config/routes.rb
db/migrate/20240713180919_enable_pg_bigm_extension.rb
docs/UPGRADE.md

#612 の続きで、pg_bigmを使った検索を可能にします。
pg_searchがpg_bigmに対応していないので、無理やり（！）対応させます。
pg_bigmはPostgreSQLの拡張モジュールで、日本語等での全文検索を行うためのものです。
https://github.com/pgbigm/pg_bigm/blob/REL1_2_STABLE/docs/pg_bigm.md
- Related to #612 
- Fixes #31

pg_bigmを使った検索を有効にする

---

config/environments/development.rb
config/environments/production.rb
config/initializers/session_store.rb

これはセッションストアをRedisにする修正ですが、以下の2点を変更しています。
* キャッシュストアとしてRedisを使うように変更
* ただし、sidekiqで使ってるはずの`REDIS_URL`をそのまま使うのではなく、`REDIS_CACHE_URL`で設定されるRedisを使用します
* セッションストアとしてキャッシュを使うように変更
* 別解として「Sidekiqで使うRedis」「キャッシュで使うRedis」「セッションに使うRedis」を全部分けるという選択肢もありますが、そこまでこだわる必要があるかどうか不明だったので2番目と3番目を同一にしています
キャッシュ用のRedisは`REDIS_CACHE_URL`という環境変数で設定しています。`REDIS_URL`と同じ値に設定してもよいですし、`redis://${ props.cache }:6379/1`などと別データベースを指定してもよいかもしれません。
注意点として、セッションに使う場合はEvictionで勝手に既存のセッションを消されたりしないよう十分なサイズを確保する必要があります。
また、開発環境でも`REDIS_CACHE_URL`が設定されていて、かつ`tmp/caching-dev.txt`が存在する場合にはRedisを使うようになります。
`tmp/caching-dev.txt`は`rails dev:cache`でON/OFFがトグルできるようになっています。

use redis for cache and session store

---

app/views/decidim/accountability/results/_timeline.html.erb

Fix invalid escaping(?) in timeline in accountability module.
- Related to https://github.com/decidim/decidim/pull/12547

fix: use `decidim_sanitize_admin` instead of `decidim_escape_translated`

---

Dockerfile

`docker compose build`を行った際、`WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 1)`というwarningが出るのを修正します。

Dockerfile: fix warning

---

app/queries/decidim/accountability/filtered_results.rb
app/queries/decidim/blogs/filtered_posts.rb
app/queries/decidim/debates/filtered_debates.rb
config/initializers/comments_count.rb

統計のコメント数について、集計対象を増やします。
- Fixes #?

Add `:comments_count` for stats of Accountability, Blogs, Debates, and Sortitions components

---

config/application.rb
config/environments/development.rb
docs/UPGRADE.md

#630 はDecidimのバージョンをあげると動かなくなるので、（あまり）依存しない形に修正しました。
いずれにしても、v0.28になれば不要になるため、更新時には消す必要があります。
initializerは上書きできるという説もあったのですが、いろいろ試してみたところでは結局session_storeの差し替えには失敗してしまうようでした。
そのため、initializerのgroup(指定しない場合は`:default`)を変更することで`run_initializers`実行時に無視されるよう修正したところ、正しく修正されるようだったのでこれにしてみます。
- Related to #629 , #630

セッションストアとしてcache_storeを使えるよう`DecidimApp::Application`を修正

---

config/environments/production.rb

※ #630 をマージされているのが前提です。
productionのセッションも #630 に合わせて修正するものです。
- Related to #630

fix session in production

---

Gemfile
Gemfile.lock
etc/nginx/conf.d/default.conf

cityOSをdecidim-cfjに導入する
- [ x ] Add `CHANGELOG` upgrade notes, if required
- [ x ] If there's a new public field, add it to GraphQL API
- [ x ] Add documentation regarding the feature 
- [ x ] Add/modify seeds
- [ x ] Add tests
- [ x ] Another subtask

city_osのomniauthを導入

---

config/environments/development.rb
config/environments/production.rb

expirationの設定を追加します。
- RedisCacheStoreを使っているキャッシュについては、`REDIS_CACHE_EXPIRES_IN`という新しい環境変数を追加します。デフォルトは60分にしています。
- cache_storeを使っているセッションについては、`Decidim.config.expire_session_after`の値を使うようにしています。
- Fixes #?

Use `expire_session_after` for session, `REDIS_CACHE_EXPIRES_IN` for cache

---

config/locales/ja.yml

提案のボタンの翻訳を「オススメする」に変更します
- Fixes #?

fix: decidim.endorsement_buttons_cell.endorse

---

app/packs/src/decidim/cfj/editor/extensions/iframe/index.js
spec/rails_helper.rb
spec/system/comment_sort_spec.rb

#658  のやり直しです。
tiptapが以下のような警告を出してきてるので対応します。
> [tiptap warn]: BREAKING CHANGE: "defaultOptions" is deprecated. Please use "addOptions" instead.
テストのエラー避けにCapybara.raise_server_errorsの修正もcherry-pickしています。
またテストでのCSPの上書きにも対応しています。
- Related to #658

fix: suppress warnings in iframe

---

config/initializers/pg_search_override.rb
spec/system/comment_sort_spec.rb

警告避けのため、`PgSearch::ScopeOptions::FEATURE_CLASSES`を再定義する前にremove_constします。
（本当は一瞬定数が消えるためthread safeではない処理なので望ましくないですが、初期化時の実行だからまあ大丈夫かなというところです）
- Fixes #?

fix `warning: already initialized constant`

---

lib/tasks/i18n_yaml.rake

デバッグ用に使うためのrake taskを追加します。
Railsで読み込んでいるlocale/config以下のデータを全部読み込んで出力します。
出力はキーが`.`区切りで並ぶように出力されます。
なおfakerはダミーのデータが多すぎるのでskipするようにしています。
```console
$ bin/rails i18n_yaml:dump_all > tmp/dump_ja.yml
```
- Fixes #?

feat: add rake task `i18n_yaml:dump_all`

---

config/initializers/decidim_override.rb

`editor_image`の権限を修正します。
`Decidim::Admin::Permissions#permissions`で定義されている権限を修正するため`DecidimAdminPermissionsPatch`をprependしています。指定した条件を満たす場合は`allow!`、満たさない場合は`super`で元のメソッドを呼び出しています。
元にしているのは https://github.com/decidim/decidim/pull/13772 ですが、こちらとは実行順序が違っているので注意が必要です。
ですが、以下の理由により先頭にチェックを突っ込む方法で問題ないと考えています。
なお、コードの通りここで権限を適用する(`allow!`を実行する)条件は以下になります。
- `user`が存在する
- `permission_action.scope == :admin`を満たす
- `permission_action.subject == :editor_image`を満たす
- （その他いろいろ）
よって、上記の条件を満たなさいものについては、実行順序が前後しても問題ないはずです。
元のコードの各行・ブロックごとに確認していきます：
- `return permission_action if managed_user_action?`
- 挿入している条件は`permission_action.subject == :managed_user`ではないので無視して良さそうです
- `unless permission_action.scope == :admin ....`
- `permission_action.scope == :admin` ではないので無視して良さそうです
- `unless user ....`
- …

fix: editor_image permissions for process admin

---

app/views/layouts/decidim/header/_main_links_mobile_account.html.erb
config/locales/en.yml
config/locales/ja.yml

モバイルで下の「アカウント」ボタンを押した時に出てくるドロップダウンのあいさつメッセージを正しく`I18n.t()`で置き換えられるように修正します。
- Fixes #?

fix: greeting in mobile account dropdown

---

app/cells/decidim/assemblies/content_blocks/highlighted_assemblies_settings_form/show.erb
app/cells/decidim/conferences/content_blocks/highlighted_conferences_settings_form/show.erb
app/cells/decidim/participatory_processes/content_blocks/highlighted_processes_settings_form/show.erb
config/initializers/decidim_override.rb

`Decidim.max_results_options`という設定を追加して、表示する要素の最大量のdropdown listの内容を指定できるようにします。
- Fixes #?

fix: max_results options in highlighted settings

---

config/application.rb

#638 ではv0.27.x用のcookie session storeを無効化するためのhackを導入しました。
decidim-cfjもv0.28.xになり、このhackは不要になったので消しておきます。
ローカルの開発環境ではこの変更後もRedisでセッション管理していることは確認済みです（が、安全のため他の環境でも丁寧に確認した方が良さそうではあります）。
- Related to #638

fix: remove hack to skip session_store

---

app/packs/src/decidim/cfj/editor/extensions/simple_image/index.js
app/packs/src/decidim/editor/extensions/decidim_kit/index.js

画像が欠落しないようにするため、標準のImageではない画像についてはインライン・編集不可・ダイアログ未対応といったシンプルな画像にするよう修正してみます。
- Fixes #?

add editor extension: SimpleImage

---

app/views/decidim/shared/_filters.html.erb

Decidimのフィルターのうち、候補が1つしかないチェックボックスのフィルターは表示させないようにします。
- Fixes #?

fix: Hide filter if only a single checkbox is present

---

config/initializers/omniauth_logging.rb

OmniAuthでログインした際にRailsのログに以下のような情報を出力するようにします。
```
[OmniAuth] Duration: 2025-03-03 20:08:09 +0900 - 2025-03-03 20:08:09 +0900, Provider: line_login, UID: UXXXXXXXXXXXXX, Email: N/A, Auth Data: #<OmniAuth::AuthHash credentials=#<OmniAuth::AuthHash expires=true expires_at=1743592089 refresh_token="XXXXXXXXXXXXx" token="XXXXX.XXXXX-XXXXXX-XXXXXXXXXXX-XXXXXX.XXXXXX"> extra=#<OmniAuth::AuthHash> info=#<OmniAuth::AuthHash::InfoHash email=nil image=nil name="foobar" user_id="XXXXX"> provider="line_login" uid="XXXXX">
```
- Fixes #?

feat: `OmniAuth::Logging` and subscribe hook

---

app/packs/src/decidim/cfj/editor/extensions/iframe/index.js

iframeを許可するドメインのチェックをコード内で行っていたのですが、CSPがあるのでCSPにおまかせすることにします。
- Fixes #?

fix: iframe: allow any domains

---

Dockerfile

https://github.com/TheDesignium/omniauth-cityos-dcp/issues/3#issuecomment-2720135934 の対応で、docker環境でもseleniumのテストできるよう、イメージに`chromium-driver`を追加しておきます。
- Fixes #?

fix: add `chromium-driver`

---

app/views/decidim/application/_document.html.erb
config/initializers/decidim_override.rb

meetingの添付ドキュメントについて、外部リンクの扱いをやめるよう修正します。
その際、cellからpartialを呼ぶ時にアプリ側のviewsが読み込まれないようだったので、`Cell::ViewModel.view_paths`も修正してみます。
- Fixes #?

fix: disable external link to attached documents

---

app/packs/src/decidim/cfj/editor/extensions/simple_image/index.js

画像アップロードの挙動に問題があるようなので、SimpleImage拡張内のsetImageを消してみます。
- Fixes #?

remove setImage in SimpleImage; use original function

---

config/secrets.yml

現状では環境変数を設定しないとlocaleが`en`になるため、無設定でも`ja`になるよう修正します。
環境変数`DECIDIM_DEFAULT_LOCALE`を設定すれば`en`にもできます。

fix: default_locale should be `ja`

---

app/packs/stylesheets/decidim/cfj/buttons.scss
app/packs/stylesheets/decidim/cfj/decidim.scss
app/packs/stylesheets/decidim/cfj/settings.scss
app/packs/stylesheets/decidim/decidim_application.scss

都合により #701 のブランチへのPRになっているので、先に #701 がマージされている前提のPRです。
独自に上書きして修正しているCSSについて、不要になっていると思われるものを消します。
- `buttons.scss`については #96 で追加したものですが、redesignによりデザインが大きく変わったこともあり、現在は適用されていません。現在のボタンに合わせて修正することもできなくはないですが、現状のデザインでも特に不満がないのであればこのまま追加したCSS側を消すのでもいいかな？と思われます。
- `decidim.scss`への修正についても、現在該当するクラス名のクラスが使われていないようでした
- `settings.scss`の`$paragraph`ですが、これも使われていないようでした。なお他の`settings.scss`で定義されているCSS変数は現在も使われているようです。
- Fixes #?

fix: remove old styles

---

spec/mailers/reported_mailer_spec.rb

メールのテストと合わせて、メール内ロゴのURLについてのテストを追加しておきます。
- Fixes #?

Add mailer spec with logo test

---

config/locales/ja.yml
spec/mailers/notifications_digest_mailer_spec.rb

Add Japanese translations for `notifications_digest_mailer.*.real_time`

---

app/cells/decidim/comments/comment_form/opinion.erb
app/jobs/purge_component_cache_job.rb
app/views/decidim/proposals/proposals/_proposal_aside.html.erb
config/initializers/decidim_override.rb
config/locales/component_settings.ja.yml

コンポーネントの設定(settings)に追加して、「共有」ボタンと「あなたの意見」ボタンを非表示にする設定を追加します。
設定は管理画面でのコンポーネントの設定画面から行います。チェックボックスが追加されるので、チェックを入れれば非表示になります。
この設定が行われないコンポーネント種別の場合はチェックボックスが表示されません。現状は提案コンポーネントとディベートコンポーネントが対象です。
なお個別のコンポーネント単位ではなく、コンポーネント種別まるごと適用になるはずです。
コメントの「あなたの意見」ボタンは、cellごとキャッシュされているため、単純に設定を変更しただけでは一定期間キャッシュが聞いて表示・非表示が切り替わりません。そのため、コンポーネントの設定が更新されるとコメントフォームのキャッシュをpurgeする処理（Job）を追加しています。
関係ないキャシュも一部purgeされてしまうようですが、（多少遅くなることはあっても）挙動には影響しないはずです。
- Fixes #?

feat: 「共有」ボタンと「あなたの意見」ボタンを非表示にする設定を追加

---

config/locales/component_settings.en.yml

#720 で英語版でも日本語のコメントが表示されてしまうので追加しておきます。
- Related to #720
英語版では以下のようになります。

fix: add locales in EN

---

app/views/layouts/decidim/footer/_main_links.html.erb

フッターにHelp等をいれるものです。これもv0.29.2からのコピーです。
- Fixes #?
↓これの「Help」になるはずです。設定によって項目は変わるはずです（ページを増やせる）。

fix: add footer_topics in footer

---

app/views/decidim/shared/_filters.html.erb

v0.29.2の変更に合わせて`aria-hidden`属性を削除します。
アクセシビリティのための修正（読み上げさせてなかったものを読み上げられるようにする）なので、通常のブラウザで閲覧する分には挙動は変わらないはずです。

fix: remove aria attribute as v0.29.2

---

config/locales/ja.yml
config/locales/navigation_maps.ja.yml

ナビゲーションマップの管理画面の翻訳が足りてなかったので追加します。
- Fixes #?

fix: add navigation_maps.ja.yml

---

app/views/decidim/devise/invitations/edit.html.erb

認証を必須にしている場合に、プライベート参加者のアカウント作成ページで、利用規約が旧URLになっており、閲覧できない問題の修正
- Fixes #?

fix: invitation edit view template terms-of-service

---

app/views/decidim/debates/debates/show.html.erb

ディベートで正しく動いていなかったのを修正します。
- Related to #720
----
----
----

fix: ディベートでの「共有」ボタンと「あなたの意見」ボタン非表示設定を修正

---

app/views/decidim/proposals/collaborative_drafts/_collaborative_draft_aside.html.erb

提案コンポーネントの共同草案で問題があったようなので修正します。
- Related to #720
----
----
----

fix: 提案・共同草案での「共有」ボタンと「あなたの意見」ボタン非表示設定を修正

---

app/views/decidim/admin/officializations/index.html.erb

参加者一覧でnicknameが空のユーザがいた場合にエラーになる問題の修正
- Fixes #?

fix: 管理画面でnicknameが空のユーザーのエラーを修正

---

config/initializers/decidim_override.rb
config/locales/ja.yml
decidim-user_extension/app/views/decidim/devise/registrations/new.html.erb
docs/UPGRADE.md
spec/forms/decidim/registration_form_nickname_spec.rb
spec/system/user_registration_nickname_spec.rb

日本語のユーザを作成する際に、nicknameが日本語になってしまい場合に登録できない場合があるため、任意入力に変更する対応
- Fixes #?

fix: nickname validation error

---

spec/mailers/newsletter_mailer_spec.rb

`NewsletterMailer`のテストを追加します。
`Decidim::CloudfrontLogoHelper`のテストも兼ねているもので、そのためにロゴ画像のある場合のテストも追加しています。
- Fixes #?

feat: add `NewsletterMailer` spec
